import = [
    "~/.config/alacritty/themes/themes/xterm.toml"
]

[colors.primary]
background = '#000000'

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500

[font]
size = 13

[font.bold]
#family = "ZedMono NF Extd"
family = "FiraCode NerdFont"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
#family = "ZedMono NF Extd"
family = "FiraCode NerdFont"
style = "Italic"

[font.normal]
#family = "ZedMono NF Extd"
family = "FiraCode NerdFont"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

#[mouse.url]
#launcher = "xdg-open"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.9

# [window.dimensions]
# columns = 80
# lines = 24

[window.padding]
x = 0
y = 0
