# import = [
#  		"~/.config/alacritty/themes/new_themes/iTerm2 Default.toml"
# ]
import = [
 		"~/.config/alacritty/themes/themes/xterm.toml"
]

# [colors.primary]
# background = '#000000'
[colors.normal]
blue = '#00bbff'

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500

[font]
size = 8.5

[font.normal]
# family = "ZedMono NF Extd"
# family = "FiraCode Nerd Font"
family = "Source Code Pro"
# family = "Hack NerdFont"
# family = "JetBrainsMono NFM"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

#[mouse.url]
#launcher = "xdg-open"

[scrolling]
history = 10000
multiplier = 3

# [window]
# opacity = 0.9

[window.dimensions]
columns = 80
lines = 24
