all:
	gcc -o mybar mybar.c print_battery_status.c print_cpu_stat.c print_disk_space.c print_microphone_volume.c print_time.c print_used_memory.c print_volume.c print_internet_status.c -Wall -lm -lasound -O2 -s
clear:
	rm mybar
